#!/usr/bin/env python3
"""
actuals-pull.py — Pull monthly sales actuals from Flieber API (Amazon) + Bol Retailer API (Bol.com)
Outputs JSON to stdout for the calling subagent to upsert via SQL.

Usage:
  python3 actuals-pull.py --month 2026-04              # Specific month
  python3 actuals-pull.py --year 2026                   # All completed months in year
  python3 actuals-pull.py                               # All completed months current year
  python3 actuals-pull.py --month 2026-04 --output /tmp/actuals.json  # Write to file

Sources:
  Amazon (FBA-US, FBA-CA, FBA-UK, FBA-EU) → Flieber GraphQL API
  Bol.com (BOL.COM)                        → Bol Retailer API (shipments)

Output format: JSON array of { product_id, channel_id, sales_month, units_actual, source }
"""

import sys
import json
import base64
import urllib.request
import urllib.error
from datetime import date
from calendar import monthrange
from collections import defaultdict

# ── Flieber Config ──────────────────────────────────────────────────────────
FLIEBER_API_KEY = "019cca1e-4959-72af-8113-f95bb6dba3a1:iJd1NgmpCqzORumpBDNjmQSMTa1LisjrKLPXXM4n1os"
FLIEBER_GQL = "https://app.flieber.com/api/graphql"

# ── Bol Config ──────────────────────────────────────────────────────────────
BOL_CLIENT_ID = "53af1986-94df-475f-96b1-f2c5cabd0038"
BOL_CLIENT_SECRET = "wg(WEhxW!b@fcTE0K@TdY33sJoi!OkxHPY8vnXxO4NP+P7aXTAvVi1y7peUn?+33"
BOL_TOKEN_URL = "https://login.bol.com/token"
BOL_BASE_URL = "https://api.bol.com"
BOL_API_VERSION = "application/vnd.retailer.v10+json"

# ── Channel ID mappings (from puzzlup_channels) ────────────────────────────
CHANNEL_IDS = {
    "FBA-US": 30,   # AMZ USA
    "FBA-CA": 31,   # AMZ CA
    "FBA-UK": 32,   # AMZ UK
    "BOL.COM": 33,  # BOL.COM
    "FBA-EU": 35,   # AMZ EU (consolidated)
}

# ── EAN → product_id mapping (from Puzzlup_Product_Info) ───────────────────
# Loaded dynamically but here's the static fallback from DB
EAN_TO_PRODUCT = {
    "5419980047489": 1,   # MAT ECO 1500
    "5419980047441": 2,   # Qualico MAT GIFT 3000
    "5419980414779": 3,   # TRAY WHITE GIFT 1500
    "5419980047465": 4,   # MAT GIFT 3000
    "5419980047472": 5,   # MAT ECO 3000
    "5419980414755": 6,   # BAG LUX 1500
    "5419980047427": 7,   # Qualico MAT GIFT 1500
    "5419980047496": 8,   # BOARD GIFT 1500
    "5419980047458": 9,   # BOARD GIFT 1000 / MAT GIFT 1500 (dup EAN — id 12 too)
    "5419980414748": 10,  # MAT LUX 1500
    "5419980414724": 11,  # MAT GIFT 5000
    "5419980414731": 13,  # MAT WHITE GIFT 1500
    "5419980414700": 14,  # TRAY BLACK GIFT 1500
    "5419980414762": 15,  # TRAY BLACK GIFT 3000
    "5419980414717": 16,  # MAT GIFT 1000
}

# Flieber fulfillmentChannel+salesChannel → our channel name
FLIEBER_CHANNEL_RULES = [
    ("AFN", "Amazon.com",    "FBA-US"),
    ("AFN", "Amazon.ca",     "FBA-CA"),
    ("AFN", "Amazon.co.uk",  "FBA-UK"),
    ("AFN", "Amazon.",       "FBA-EU"),   # catch-all for .de/.fr/.nl/.es/.it/.se/.pl/.com.be
    ("AFN", "Non-Amazon",    "FBA-EU"),   # Pan-EU / MCF orders still count as EU
]

# ── Flieber SKU → product_id mapping ────────────────────────────────────────
# Loaded dynamically from --sku-map-file (generated by subagent from
# flieber_product_skus table). Falls back to hardcoded map if no file given.
# Amazon channels only: 30=FBA-US, 31=FBA-CA, 32=FBA-UK, 35=FBA-EU
FLIEBER_SKU_TO_PRODUCT = {}  # populated at runtime

# Hardcoded fallback built from flieber_product_skus (May 2026)
_FALLBACK_SKU_MAP = {
    # product_id=1 (MAT ECO 1500)
    "USA_1500_ECOMAT": 1, "CA_1500_ECOMAT": 1, "UK_1500_MAT_ECO": 1,
    "1500 Eco packaging - MFN": 1, "1500 Eco packaging": 1, "1500_ECO_BL_FBM_ES": 1,
    # product_id=3 (TRAY WHITE 1500)
    "TRAYS_WH_FBA_USA": 3, "TRAY_WH_FBA_UK": 3, "TRAYS_WH_FBA_EU": 3,
    "TRAYS_WH_FBM_EU": 3,
    # product_id=4 (MAT GIFT 3000)
    "USA_3000_MAT": 4, "UK_3000_MAT": 4,
    "57-SH7J-DGGT": 4, "B09WTR77CV": 4, "3000_GIFT_BL_FBM_ES": 4,
    # product_id=5 (MAT ECO 3000)
    "USA_3000_ECOMAT": 5, "CA_3000_ECOMAT": 5, "UK_3000_MAT_ECO": 5,
    "PR-925M-S42K-stickerless": 5, "PR-925M-S42K": 5, "3000_ECO_BL_FBM_ES": 5,
    # product_id=8 (BOARD 1500)
    "PB1500": 8,
    # product_id=10 (MAT LUX 1500)
    "1500_LUX_BL_FBA_USA": 10, "1500_LUX_BL_FBA_UK": 10,
    "1500_LUX_BL_FBA_EU": 10, "1500_LUX_BL_FBM_EU": 10,
    # product_id=11 (MAT GIFT 5000)
    "5000_GIFT_BL_FBA_USA": 11, "5000_GIFT_BL_FBA_UK": 11,
    "5000_GIFT_BL_FBA_EU": 11, "5000_GIFT_BL_FBM_EU": 11,
    # product_id=12 (MAT GIFT 1500)
    "USA_1500_MAT": 12, "UK_1500_MAT": 12,
    "X3-WVS4-ZZPX": 12, "6C-I6V4-8TV4": 12, "1500_GIFT_BL_FBM_ES": 12,
    # product_id=13 (MAT WHITE GIFT 1500)
    "1500_GIFT_WH_FBA_EU": 13,
    # product_id=14 (TRAY BLACK 1500)
    "Puzzl_Tray": 14, "PUZZL_TrAY": 14, "Puzzl_Tray_UK": 14,
    "PUZZL_TRAY_DE": 14, "TRAYS_BL_FBM_EU": 14, "TRAYS_BL_FBM_FR": 14,
    # product_id=15 (TRAY BLACK 3000)
    "TRAY_BL_2SET_FBA_USA": 15, "TRAY_BL_2SET_FBA_UK": 15,
    "TRAY_BL_2SET_FBA_EU": 15, "TRAY_BL_2SET_FBM_EU": 15,
    # product_id=16 (MAT GIFT 1000)
    "1000_GIFT_BL_FBA_USA": 16, "1000_GIFT_BL_FBA_UK": 16,
    "1000_GIFT_BL_FBA_EU": 16, "1000_GIFT_BL_FBM_EU": 16,
}

# SKUs to silently skip (webshop, Shopify, non-forecast channels)
SKIP_SKUS = {"1500ECO_WOO", "1500GIFT_WOO", "3000GIFT_WOO", "3000ECO_WOO",
             "TRAYS_BL_WOO", "TRAYS_WH_WOO", "TRAY_BL_2SET_WOO",
             "5000GIFT_BL_WOO", "1000GIFT_BL_WOO", "1500_LUX_BL_WOO",
             "1500_GIFT_WH_WOO", "BOARD_WOO",
             "41333546352830", "41404728934590", "41690748616894",
             "41690748616894.", "41690748616896", "42386895995070",
             "Puzzle mat large"}

# ── Flieber API ──────────────────────────────────────────────────────────────
def flieber_gql(query, variables=None):
    payload = {"query": query}
    if variables:
        payload["variables"] = variables
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        FLIEBER_GQL, data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {FLIEBER_API_KEY}",
            "User-Agent": "Mozilla/5.0 (qualico-actuals/2.0)"
        }
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        result = json.loads(resp.read().decode())
    if "errors" in result:
        raise Exception(f"Flieber error: {result['errors']}")
    return result["data"]


SALES_QUERY = """
query GetSales($startDate: DateTime!, $endDate: DateTime!, $offset: Int!) {
  sales(
    filters: { startDate: $startDate, endDate: $endDate }
    pagination: { limit: 500, offset: $offset }
  ) {
    pageInfo { hasNext totalCount }
    items {
      sku
      quantity
      fulfillmentChannel
      salesChannel
    }
  }
}
"""


def fetch_flieber_month(year, month):
    """Fetch Amazon sales for a month via Flieber API. Returns aggregated records."""
    last_day = monthrange(year, month)[1]
    start = f"{year}-{month:02d}-01T00:00:00Z"
    end = f"{year}-{month:02d}-{last_day}T23:59:59Z"

    all_items = []
    offset = 0
    while True:
        data = flieber_gql(SALES_QUERY, {"startDate": start, "endDate": end, "offset": offset})
        items = data["sales"]["items"]
        has_next = data["sales"]["pageInfo"]["hasNext"]
        all_items.extend(items)
        if not has_next:
            break
        offset += 500

    # Aggregate by channel + product_id (resolved via FLIEBER_SKU_TO_PRODUCT)
    totals = defaultdict(int)  # (channel_name, product_id) → units
    skipped_channels = defaultdict(int)
    unresolved = defaultdict(int)
    for item in all_items:
        fc = item.get("fulfillmentChannel", "")
        sc = item.get("salesChannel", "")
        sku = item.get("sku", "")

        # Skip webshop/non-forecast SKUs
        if sku in SKIP_SKUS:
            continue

        # Skip Bol channel in Flieber (unreliable — we use Bol Retailer API)
        if fc == "manual":
            continue

        # Resolve channel
        channel = None
        for rule_fc, rule_sc, name in FLIEBER_CHANNEL_RULES:
            if fc == rule_fc and rule_sc.lower() in sc.lower():
                channel = name
                break
        if not channel:
            skipped_channels[f"{fc}/{sc}"] += item.get("quantity", 0)
            continue

        # Resolve product
        product_id = FLIEBER_SKU_TO_PRODUCT.get(sku)
        if not product_id:
            unresolved[sku] += item.get("quantity", 0)
            continue

        totals[(channel, product_id)] += item.get("quantity", 0)

    if skipped_channels:
        print(f"  [Flieber] Skipped channels: {dict(skipped_channels)}", file=sys.stderr)
    if unresolved:
        print(f"  [Flieber] ⚠️  Unresolved SKUs: {dict(unresolved)}", file=sys.stderr)

    print(f"  [Flieber] {len(all_items)} raw orders → {len(totals)} channel/product combos", file=sys.stderr)
    return totals


# ── Bol Retailer API ────────────────────────────────────────────────────────
_bol_token_cache = None

def bol_get_token():
    global _bol_token_cache
    if _bol_token_cache:
        return _bol_token_cache
    creds = base64.b64encode(f"{BOL_CLIENT_ID}:{BOL_CLIENT_SECRET}".encode()).decode()
    data = "grant_type=client_credentials".encode()
    req = urllib.request.Request(
        BOL_TOKEN_URL, data=data,
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/x-www-form-urlencoded"
        }
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        result = json.loads(resp.read().decode())
    _bol_token_cache = result["access_token"]
    return _bol_token_cache


def bol_api_get(path, params=None):
    token = bol_get_token()
    url = f"{BOL_BASE_URL}{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(
        url, headers={
            "Authorization": f"Bearer {token}",
            "Accept": BOL_API_VERSION
        }
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def fetch_bol_month(year, month):
    """Fetch Bol.com shipments for a month. Returns { ean: unit_count }."""
    from datetime import datetime
    last_day = monthrange(year, month)[1]
    month_start = datetime(year, month, 1)
    month_end = datetime(year, month, last_day, 23, 59, 59)

    ean_totals = defaultdict(int)
    page = 1
    total_shipments = 0
    pages_without_match = 0

    while True:
        data = bol_api_get("/retailer/shipments", {"fulfilment-method": "FBB", "page": page})
        shipments = data.get("shipments", [])
        if not shipments:
            break

        found_in_range = False
        found_before_range = False

        for s in shipments:
            ship_dt_str = s.get("shipmentDateTime", "")
            # Parse ISO datetime like "2026-05-07T15:45:17+02:00"
            try:
                # Strip timezone for simple comparison
                dt_clean = ship_dt_str[:19]
                ship_dt = datetime.strptime(dt_clean, "%Y-%m-%dT%H:%M:%S")
            except (ValueError, IndexError):
                continue

            if ship_dt < month_start:
                found_before_range = True
                continue
            if ship_dt > month_end:
                continue  # Future month, keep going back

            found_in_range = True
            total_shipments += 1
            for item in s.get("shipmentItems", []):
                ean = item.get("ean", "")
                if ean:
                    ean_totals[ean] += 1

        # If all shipments on this page are before our target month, stop
        if found_before_range and not found_in_range:
            pages_without_match += 1
            if pages_without_match >= 2:
                break  # Two consecutive pages fully before range = done
        else:
            pages_without_match = 0

        page += 1
        if page > 200:  # Safety limit
            print(f"  [Bol] Hit 200 page limit", file=sys.stderr)
            break

    print(f"  [Bol] {total_shipments} shipments in month, {len(ean_totals)} unique EANs, scanned {page} pages", file=sys.stderr)
    return ean_totals


# ── Main logic ──────────────────────────────────────────────────────────────
def completed_months_in_year(year):
    today = date.today()
    months = []
    for m in range(1, 13):
        last = date(year, m, monthrange(year, m)[1])
        if last < today:
            months.append((year, m))
    return months



def main():
    global FLIEBER_SKU_TO_PRODUCT
    import urllib.parse  # needed for bol_api_get
    args = sys.argv[1:]
    output_file = None
    sku_map_file = None

    if "--output" in args:
        idx = args.index("--output")
        output_file = args[idx + 1]
        args = args[:idx] + args[idx+2:]

    if "--sku-map-file" in args:
        idx = args.index("--sku-map-file")
        sku_map_file = args[idx + 1]
        args = args[:idx] + args[idx+2:]

    # Load SKU map: dynamic from file (Supabase flieber_product_skus) or fallback
    if sku_map_file:
        with open(sku_map_file) as f:
            FLIEBER_SKU_TO_PRODUCT = json.load(f)
        print(f"Loaded {len(FLIEBER_SKU_TO_PRODUCT)} SKUs from {sku_map_file}", file=sys.stderr)
    else:
        FLIEBER_SKU_TO_PRODUCT = _FALLBACK_SKU_MAP.copy()
        print(f"Using fallback SKU map ({len(FLIEBER_SKU_TO_PRODUCT)} SKUs)", file=sys.stderr)

    if "--month" in args:
        idx = args.index("--month")
        month_str = args[idx + 1]
        year, month = int(month_str[:4]), int(month_str[5:7])
        months_to_pull = [(year, month)]
    elif "--year" in args:
        idx = args.index("--year")
        year = int(args[idx + 1])
        months_to_pull = completed_months_in_year(year)
    else:
        months_to_pull = completed_months_in_year(date.today().year)

    print(f"Pulling actuals for: {[f'{y}-{m:02d}' for y,m in months_to_pull]}", file=sys.stderr)

    all_records = []

    for year, month in months_to_pull:
        sales_month = f"{year}-{month:02d}-01"
        print(f"\n── {year}-{month:02d} ──", file=sys.stderr)

        # 1. Amazon channels via Flieber API (product_id already resolved)
        flieber_totals = fetch_flieber_month(year, month)
        for (channel_name, product_id), units in flieber_totals.items():
            channel_id = CHANNEL_IDS.get(channel_name)
            if not channel_id:
                continue
            all_records.append({
                "product_id": product_id,
                "channel_id": channel_id,
                "sales_month": sales_month,
                "units_actual": units,
                "source": "flieber_api"
            })

        # 2. Bol.com via Retailer API
        bol_totals = fetch_bol_month(year, month)
        for ean, units in bol_totals.items():
            product_id = EAN_TO_PRODUCT.get(ean)
            if not product_id:
                print(f"  [Bol] Unknown EAN: {ean} ({units} units)", file=sys.stderr)
                continue
            all_records.append({
                "product_id": product_id,
                "channel_id": CHANNEL_IDS["BOL.COM"],
                "sales_month": sales_month,
                "units_actual": units,
                "source": "bol_retailer_api"
            })

    # Aggregate duplicates (same product+channel+month)
    agg = defaultdict(lambda: {"units": 0, "source": ""})
    for r in all_records:
        key = (r["product_id"], r["channel_id"], r["sales_month"])
        agg[key]["units"] += r["units_actual"]
        agg[key]["source"] = r["source"]

    final_records = [
        {
            "product_id": k[0],
            "channel_id": k[1],
            "sales_month": k[2],
            "units_actual": v["units"],
            "source": v["source"]
        }
        for k, v in agg.items()
    ]

    print(f"\n✅ Total records: {len(final_records)}", file=sys.stderr)

    # Output
    output = json.dumps(final_records, indent=2)
    if output_file:
        with open(output_file, "w") as f:
            f.write(output)
        print(f"Written to {output_file}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
